import { StyleSheet, Platform, StatusBar as RNStatusBar } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F4F8',
    paddingTop: Platform.OS === 'android' ? RNStatusBar.currentHeight : 0,
  },
  container: {
    flex: 1,
  },
  contentWrapper: {
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    height: 75,
    marginTop: Platform.OS === 'android' ? -RNStatusBar.currentHeight : 0,
  },
  profileIcon: {
    padding: 3,
    top: 10,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    top: 10,
  },
  logoutButtonText: {
    color: '#FFFFFF',
    marginLeft: 5,
    fontWeight: 'bold',
    fontSize: 12,
  },
  welcomeText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
    marginTop: 20,
  },
  dateText: {
    fontSize: 15,
    color: '#6B7280',
    marginBottom: 20,
  },
  currentQueueCard: {
    backgroundColor: '#053F5C',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    marginBottom: 15,
    shadowColor: '#053F5C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  currentQueueTitle: {
    fontSize: 16,
    color: 'white',
    opacity: 0.9,
  },
  currentQueueNumber: {
    fontSize: 56,
    fontWeight: 'bold',
    color: 'white',
    marginVertical: 10,
  },
  refreshButton: {
    flexDirection: 'row',
    backgroundColor: '#DC3545',
    borderRadius: 12,
    padding: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    shadowColor: '#DC3545',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  refreshButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  buttonDisabled: {
    backgroundColor: '#E0A1A7',
  },
  actionButton: {
    flexDirection: 'row',
    backgroundColor: '#28A745',
    borderRadius: 12,
    padding: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 25,
    shadowColor: '#28A745',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  actionButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    width: '85%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
  },
  iconBackground: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#F27F0C',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  modalTextContainer: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  modalMessage: {
    fontSize: 14,
    color: '#666',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#ccc',
    marginRight: 10,
  },
  cancelButtonText: {
    color: '#333',
    fontWeight: 'bold',
    fontSize: 16,
  },
  logoutModalButton: {
    backgroundColor: '#DC3545',
  },
  logoutModalButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  listTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 15,
  },
  listWrapper: {
    borderRadius: 16,
    marginBottom: 40,
    backgroundColor: '#FFFFFF',
    shadowColor: '#959DA5',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    overflow: 'hidden',
  },
  searchFilterSection: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    marginRight: 10,
    height: 44,
  },
  searchIcon: {
    paddingHorizontal: 12,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 8,
    paddingRight: 10,
    fontSize: 14,
    color: '#1F2937',
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 12,
    height: 44,
    borderRadius: 10,
  },
  filterButtonOnline: {
    backgroundColor: '#E0F2F1',
  },
  filterButtonOffline: {
    backgroundColor: '#FCE4EC',
  },
  filterButtonText: {
    color: '#374151',
    fontWeight: '600',
    marginLeft: 8,
    fontSize: 14,
  },
  filterButtonTextActive: {},
  tableContainer: {
    backgroundColor: 'white',
    paddingHorizontal: 15,
  },
  tableHeader: {
    flexDirection: 'row',
    paddingBottom: 10,
    paddingTop: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#F3F4F6',
  },
  tableHeaderText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#6B7280',
    textTransform: 'uppercase',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  tableCell: {
    fontSize: 14,
    color: '#374151',
  },
  ticketCell: {
    fontWeight: 'bold',
    color: '#053F5C',
  },
  nameCell: {
    fontWeight: '500',
  },
  timeCell: {
    color: '#6B7280',
  },
  statusCellContainer: {
    alignItems: 'flex-start',
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 12,
  },
  statusBadgeOnline: {
    backgroundColor: '#D1FAE5',
  },
  statusBadgeOffline: {
    backgroundColor: '#FEE2E2',
  },
  statusTextOnline: {
    color: '#065F46',
    fontSize: 12,
    fontWeight: 'bold',
  },
  statusTextOffline: {
    color: '#991B1B',
    fontSize: 12,
    fontWeight: 'bold',
  },
  emptyListText: {
    textAlign: 'center',
    paddingVertical: 40,
    color: '#6B7280',
    fontSize: 14,
  },
});

export default styles;
